bind 0.0.0.0
protected-mode no
port 6379
replicaof 100.109.122.25 6379
replica-read-only yes
replica-serve-stale-data yes
appendonly yes
appendfsync everysec
save 900 1
save 300 10
repl-timeout 60
loglevel notice
logfile /home/ubuntu/redis/logs/redis-replica.log
dir /home/ubuntu/redis/data
